Fix instructions for sysimage
I am pretty sure that this is correct now, and it was very wrong before. I am still unable to generate a sysimage, but at least the file is not correctly located and run.

I am getting the following error
```
Activating project at `~/.vscode/extensions/julialang.language-julia-1.38.2/scripts/environments/sysimagecompile/v1.8`
[ Info: Now building a custom sysimage for the environment '/home/dennishb/.julia/environments/v1.8', excluding dev packages 'Symbol[]'.
┌ Info: Included packages: 
│       - Term
│       - Revise
│       - Integrals
│       - Measurements
│       - LinearSolve
│       - Symbolics
│       - DSP
│       - SymbolicNumericIntegration
│       - PyCall
│       - AbbreviatedStackTraces
│       - StatsBase
│       - OhMyREPL
│       - PkgTemplates
│       - Tau
│       - WGLMakie
│       - Latexify
│       - Pluto
│       - IntervalRootFinding
│       - PythonCall
│       - FileIO
│       - MATLAB
│       - TaylorSeries
│       - Tools
│       - PackageCompiler
│       - Unitful
│       - TiffImages
│       - GLMakie
│       - UnicodePlots
│       - EasyFFTs
│       - AutoSysimages
└       - FFTW
[ Info: Precompile statement files: String[]
[ Info: Precompile execution files: ["/home/dennishb/.julia/environments/v1.8/sysimage_excecution_file.jl"]
[ Info: PackageCompiler: Executing /home/dennishb/.julia/environments/v1.8/sysimage_excecution_file.jl => /tmp/jl_packagecompiler_UHllQH/jl_io4aQS
[ Info: Running "sysimage_excecution_file.jl"!
[ Info: PackageCompiler: Done
⢰ [00m:35s] PackageCompiler: compiling incremental system imageER
⠙ [00m:36s] PackageCompiler: compiling incremental system imageDeclaring __precompile__(false) is not allowed in files that are being precompiled.
Stacktrace:
⣄ [00m:37s] PackageCompiler: compiling incremental system imageBool)
   @ Base ./loading.jl:1114
 [2] top-level scope
   @ ~/.julia/packages/AbbreviatedStackTraces/bVmSM/src/AbbreviatedStackTraces.jl:2
 [3] include
   @ ./Base.jl:419 [inlined]
 [4] _require(pkg::Base.PkgId)
   @ Base ./loading.jl:1367
 [5] _require_prelocked(uuidkey::Base.PkgId)
   @ Base ./loading.jl:1200
 [6] macro expansion
   @ ./lock.jl:223 [inlined]
 [7] require(uuidkey::Base.PkgId)
   @ Base ./loading.jl:1195
 [8] top-level scope
   @ /tmp/jl_OzmdgNq9yn:40
in expression starting at /home/dennishb/.julia/packages/AbbreviatedStackTraces/bVmSM/src/AbbreviatedStackTraces.jl:1
in expression starting at /tmp/jl_OzmdgNq9yn:40
✖ [00m:37s] PackageCompiler: compiling incremental system image
ERROR: LoadError: failed process: Process(`/home/dennishb/.julia/juliaup/julia-1.8.2+0.x64/bin/julia --color=yes --startup-file=no --cpu-target=native -O3 --sysimage=/home/dennishb/.julia/juliaup/julia-1.8.2+0.x64/lib/julia/sys.so --project=/home/dennishb/.julia/environments/v1.8 --output-o=/tmp/jl_0nwD0fSXyd.o /tmp/jl_OzmdgNq9yn`, ProcessExited(1)) [1]

Stacktrace:
 [1] pipeline_error
   @ ./process.jl:565 [inlined]
 [2] run(::Cmd; wait::Bool)
   @ Base ./process.jl:480
 [3] run
   @ ./process.jl:477 [inlined]
 [4] #14
   @ ~/.vscode/extensions/julialang.language-julia-1.38.2/scripts/packages/PackageCompiler/ext/TerminalSpinners.jl:157 [inlined]
 [5] spin(f::PackageCompiler.var"#14#15"{Cmd}, s::PackageCompiler.TerminalSpinners.Spinner{Base.TTY})
   @ PackageCompiler.TerminalSpinners ~/.vscode/extensions/julialang.language-julia-1.38.2/scripts/packages/PackageCompiler/ext/TerminalSpinners.jl:164
 [6] macro expansion
   @ ~/.vscode/extensions/julialang.language-julia-1.38.2/scripts/packages/PackageCompiler/ext/TerminalSpinners.jl:157 [inlined]
 [7] create_sysimg_object_file(object_file::String, packages::Vector{String}, packages_sysimg::Set{Base.PkgId}; project::String, base_sysimage::String, precompile_execution_file::Vector{String}, precompile_statements_file::Vector{String}, cpu_target::String, script::Nothing, sysimage_build_args::Cmd, extra_precompiles::String, incremental::Bool)
   @ PackageCompiler ~/.vscode/extensions/julialang.language-julia-1.38.2/scripts/packages/PackageCompiler/src/PackageCompiler.jl:359
 [8] create_sysimage(packages::Vector{Symbol}; sysimage_path::String, project::String, precompile_execution_file::Vector{String}, precompile_statements_file::Vector{String}, incremental::Bool, filter_stdlibs::Bool, cpu_target::String, script::Nothing, sysimage_build_args::Cmd, include_transitive_dependencies::Bool, base_sysimage::Nothing, julia_init_c_file::Nothing, version::Nothing, soname::Nothing, compat_level::String, extra_precompiles::String)
   @ PackageCompiler ~/.vscode/extensions/julialang.language-julia-1.38.2/scripts/packages/PackageCompiler/src/PackageCompiler.jl:510
 [9] top-level scope
   @ ~/.vscode/extensions/julialang.language-julia-1.38.2/scripts/tasks/task_compileenv.jl:94
in expression starting at /home/dennishb/.vscode/extensions/julialang.language-julia-1.38.2/scripts/tasks/task_compileenv.jl:94

 *  The terminal process "/home/dennishb/.julia/juliaup/julia-1.8.2+0.x64/bin/julia '--color=yes', '--startup-file=no', '--history-file=no', '/home/dennishb/.vscode/extensions/julialang.language-julia-1.38.2/scripts/tasks/task_compileenv.jl', '/home/dennishb/.julia/environments/v1.8'" terminated with exit code: 1. 
 *  Terminal will be reused by tasks, press any key to close it. 
```